import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/providers/redux-provider';
import AppThemeProvider from '@/lib/theme-provider';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

const notoSans = Noto_Sans({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['Arial', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} antialiased`}>
        <ReduxProvider>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <AppThemeProvider>{children}</AppThemeProvider>
          </AppRouterCacheProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
